[package]
name = "template"
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"
license = "MIT"
description = "A template for a new Rust project"
authors = ["Your Name <your.email@example.com>"]

[dependencies]
