[package]
name = "template"
version = "0.5.0"
edition = "2021"
rust-version = "1.70.0"
license = "MIT"
description = "A template for a new Rust project"
authors = ["Your Name <your.email@example.com>"]

[dependencies]
